ARG BASE_VERSION=latest
FROM gofunky/git:${BASE_VERSION}

ADD ./orbs/envorb/load.sh /usr/local/bin/envload
RUN chmod +x /usr/local/bin/envload

ARG VERSION
ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/gofunky/readmyhub" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0"
