version: 2.1

git_job: &git_job
  attach: true
  compose: docker-compose.test.yml
  base_tag: funkygit
  add_labels: true
  docker_version: 18.09.0
  context: docker-hub
  args: "VERSION=${GIT_VERSION},ALPINE=${ALPINE_VERSION}"

master_filter: &master_filter
  filters:
    branches:
      only:
        - master

pr_filter: &pr_filter
  filters:
    branches:
      ignore:
        - master

set_git_version: &set_git_version
  attach: true
  alpine_version: "3.8"
  variable: GIT_VERSION
  prepare:
    - run:
        name: Update git
        command: |
          apk add --no-cache --upgrade git
  cmd: git --version

set_alpine_version: &set_alpine_version
  attach: true
  alpine_version: "3.8"
  variable: ALPINE_VERSION
  value: "3.8"

orbs:
  orbtools: gofunky/orbtools@0.1.0

  envorb: gofunky/envorb@0.2.6

  #readmyhub: gofunky/readmyhub@dev

  docker: gofunky/docker@0.0.3

jobs:
  migrate:
    executor:
      name: docker/default
    steps:
      - attach_workspace:
          at: '.'
      - run: mv ./env ./.env
      - persist_to_workspace:
          root: .
          paths:
            - ./.env

workflows:
  #readme:
  #  jobs:
  #    - readmyhub/update:
  #        name: update_readme
  #        <<: *master_filter
  #        version: 1.1.0
  #        context: docker-hub
  build_latest:
    jobs:
    - envorb/cmd_version:
        name: set_git_version
        <<: *set_git_version
    - envorb/value:
        name: set_alpine_version
        <<: *set_alpine_version
    - migrate:
        requires:
          - set_git_version
          - set_alpine_version
    - docker/build_test_push:
        name: build_latest
        <<: [*master_filter, *git_job]
        tags: "gofunky/git:${GIT_VERSION},gofunky/git:${GIT_VERSION}-alpine${ALPINE_VERSION},gofunky/git:latest"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        cache: true
        requires:
          - migrate
          - set_git_version
          - set_alpine_version
    - docker/build_test_push:
        name: build_envload
        <<: [*master_filter, *git_job]
        tags: "gofunky/git:${GIT_VERSION}-envload,gofunky/git:${GIT_VERSION}-alpine${ALPINE_VERSION}-envload,gofunky/git:envload"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        cache: true
        add_labels: false
        path: "./envorb"
        compose: "./envorb/test/docker-compose.test.yml"
        base_tag: gittest
        args: "BASE=gofunky/git:${GIT_VERSION}-alpine${ALPINE_VERSION}"
        requires:
          - migrate
          - set_git_version
          - set_alpine_version
          - build_latest
    - docker/build_test:
        name: test_latest
        <<: [*pr_filter, *git_job]
        tags: "gofunky/git:${GIT_VERSION},gofunky/git:${GIT_VERSION}-alpine${ALPINE_VERSION},gofunky/git:latest"
        requires:
        - set_git_version
        - set_alpine_version
    - docker/build_test:
        name: test_envload
        <<: [*pr_filter, *git_job]
        tags: "gofunky/git:${GIT_VERSION}-envload,gofunky/git:${GIT_VERSION}-alpine${ALPINE_VERSION}-envload,gofunky/git:envload"
        add_labels: false
        path: "./envorb"
        compose: "./envorb/test/docker-compose.test.yml"
        base_tag: gittest
        args: "BASE=gofunky/git:${GIT_VERSION}-alpine${ALPINE_VERSION}"
        requires:
        - set_git_version
        - set_alpine_version
        - test_latest
  build_daily:
    triggers:
    - schedule:
        cron: "0 0 * * *"
        <<: *master_filter
    jobs:
    - envorb/cmd_version:
        name: daily_set_git_version
        <<: *set_git_version
    - envorb/value:
        name: daily_set_alpine_version
        <<: *set_alpine_version
    - docker/build_test_push:
        name: daily_build_latest
        <<: [*master_filter, *git_job]
        tags: "gofunky/git:${GIT_VERSION},gofunky/git:${GIT_VERSION}-alpine${ALPINE_VERSION},gofunky/git:latest,gofunky/git:stable,gofunky/git:daily"
        login: docker login -u $DOCKER_USR -p $DOCKER_PWD
        cache: true
        requires:
        - daily_set_git_version
        - daily_set_alpine_version
